[package]
name = "bevy_tiled_camera"
version = "0.1.0"
edition = "2021"
authors = ["sark"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", rev = "add1818a05ad4b8d4672197afd477ab29f8446b5", default-features = false, features = ["render"] }

[dev-dependencies]
bevy = {git = "https://github.com/bevyengine/bevy", rev = "add1818a05ad4b8d4672197afd477ab29f8446b5", features = ["png", "bevy_winit", "bevy_render"]}
assert_approx_eq = "1.1.0"