[package]
name = "bevy_tiled_camera"
version = "0.2.4"
edition = "2021"
authors = ["sark"]
homepage = "https://github.com/sarkahn/bevy_tiled_camera"
repository = "https://github.com/sarkahn/bevy_tiled_camera"
license = "MIT"
exclude = ["images/*"]
description = "A simple camera for properly displaying low resolution pixel perfect 2D games in bevy."
readme = "README.md"
keywords = ["bevy", "camera", "pixel-perfect", "low-resolution", "2d"]

[dependencies]
bevy = {version = "0.5", default-features = false, features = ["render"]}

[dev-dependencies]
bevy = {version = "0.5", default-features = false, features = ["png", "bevy_winit", "bevy_wgpu"]}