[package]
authors = ["sark"]
description = "A camera for rendering low resolution pixel art in bevy."
edition = "2021"
homepage = "https://github.com/sarkahn/bevy_tiled_camera"
keywords = ["bevy", "2d", "camera", "pixels"]
license = "MIT"
name = "bevy_tiled_camera"
readme = "README.md"
repository = "https://github.com/sarkahn/bevy_tiled_camera"
version = "0.3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = {version = "0.7", default-features = false, features = ["render"]}

[dev-dependencies]
assert_approx_eq = "1.1.0"
bevy = {version = "0.7", default-features = false, features = ["png", "bevy_winit", "bevy_render", "x11"]}
