[package]
name = "bevy_tiled_camera"
version = "0.2.1"
edition = "2021"
authors = ["sark"]
homepage = "https://github.com/sarkahn/bevy_tiled_camera"
repository = "https://github.com/sarkahn/bevy_tiled_camera"
license = "MIT"
exclude = ["images/*"]
description = "A simple camera for properly displaying low resolution pixel perfect 2D games in bevy."
readme = "README.md"

[dependencies]
bevy = "0.5"