[package]
name = "bevy_tiled_camera"
version = "0.1.0"
edition = "2021"
authors = ["sark"]
homepage = "https://github.com/sarkahn/bevy_tiled_camera"
repository = "https://github.com/sarkahn/bevy_tiled_camera"
license = "MIT"
exclude = ["images/*"]

[dependencies]
bevy = "0.5"