[package]
name = "bevy_tiled_camera"
edition = "2021"
authors = ["sark"]
homepage = "https://github.com/sarkahn/bevy_tiled_camera"
repository = "https://github.com/sarkahn/bevy_tiled_camera"
license = "MIT"
readme = "README.md"
version = "0.4.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { default_features=false, features=["render"], git = "https://github.com/bevyengine/bevy", rev = "c6222f1acc4a5d4478b5cb188f0eda24afb6546a" }
sark_grids = "0.4.0"

[dev-dependencies]
assert_approx_eq = "1.1.0"
bevy = { default-features = false, features = ["png", "bevy_winit", "render", "x11"], git = "https://github.com/bevyengine/bevy", rev = "c6222f1acc4a5d4478b5cb188f0eda24afb6546a"}
